sudo: required
services:
   - docker
   
before_install:
    - docker build -t itsyrulnikov/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true itsyrulnikov/react-test npm test -- --coverage

after_success:
    - docker build -t itsyrulnikov/udemy-multi-client ./client
    - docker build -t itsyrulnikov/udemy-multi-nginx ./nginx
    - docker build -t itsyrulnikov/udemy-multi-server ./server
    - docker build -t itsyrulnikov/udemy-multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin

- docker push itsyrulnikov/udemy-multi-client
- docker push itsyrulnikov/udemy-multi-nginx
- docker push itsyrulnikov/udemy-multi-server
- docker push itsyrulnikov/udemy-multi-worker